# IMPORTANT: After changing anything in this file, ensure validity using https://jsonformatter.org/yaml-validator

## HotkeyConfiguration - Keyboard shortcuts for the overlay
HotkeyConfiguration:
  ToggleKey: '\'
  ZoomInKey: '+'
  ZoomOutKey: '-'
  GameInfoKey: '['

## PrefetchAreas - Areas to preload so that they're hot and ready as soon as you go to them
PrefetchAreas:
 - 'Lower Kurast'

## HiddenAreas - Areas where the overlay is not needed and will be hidden
HiddenAreas:
 - 'Rogue Encampment'
 - 'Lut Gholein'
 - 'Kurast Docktown'
 - 'The Pandemonium Fortress'
 - 'Harrogath'
 - 'Forgotten Tower'
 - 'Nihlathaks Temple'

## RenderingConfiguration - Visual settings for the overlay
RenderingConfiguration:
  ## Opacity - Overlay trapsparency %
  Opacity: 0.6
  ## OverlayMode - Overlay map over in-game map / can be hidden with hotkey (ToggleKey)
  OverlayMode: false
  ## Positions - Options are: Center, TopLeft, TopRight
  Position: TopRight
  ## ToggleViaInGameMap - Auto-hide map overlay when the in-game map is hidden
  ToggleViaInGameMap: false
  ## ToggleViaInGamePanels - Auto-hide overlay when in-game panels/menus are opened
  ToggleViaInGamePanels: true
  ## Size - Overlay map maximum size
  Size: 600
  ## Rotate - Transform map image with 45 degree rotation
  Rotate: true
  ## ZoomLevel - Zoom level / can zoom in/out with hotkeys (ZoomInKey, ZoomOutKey)
  ZoomLevel: 1.5
  ## BuffPosition - Options are: Player, Top, Bottom
  BuffPosition: Bottom
  ## BuffSize - Size of the buff icons (0.8 = 80%, 1 = 100%, 1.2 = 120%)
  BuffSize: 1

## MapConfiguration -- Visual settings for icons, lines and labels
MapConfiguration:
  SuperUniqueMonster:
    IconColor: '168, 75, 255' # Purple
    IconShape: Cross
    IconSize: 8
    IconThickness: 2
  UniqueMonster:
    IconColor: '255, 75, 75' # Red
    IconShape: Cross
    IconSize: 8
    IconThickness: 2
  EliteMonster:
    IconColor: '255, 157, 0' # Orange
    IconShape: Cross
    IconSize: 8
    IconThickness: 1
  NormalMonster:
    IconColor: Gray
    IconShape: Cross
    IconSize: 8
    IconThickness: 1
  NextArea:
    IconColor: '237, 107, 0'
    IconShape: Square
    IconSize: 5
    LineColor: Chartreuse
    LineThickness: 1
    ArrowHeadSize: 3
    LabelColor: Chartreuse
    LabelFontSize: 10
    LabelFont: 'Helvetica'
  PreviousArea:
    IconColor: '255, 0, 149'
    IconShape: Square
    IconSize: 5
    LineColor: ''
    LabelColor: Chartreuse
    LabelFontSize: 10
    LabelFont: 'Helvetica'
  Waypoint:
    IconColor: '16, 140, 235'
    IconShape: Square
    IconSize: 5
  Quest:
    LineColor: Orange
    LineThickness: 1
    ArrowHeadSize: 3
    LabelColor: Orange
    LabelFontSize: 10
    LabelFont: 'Helvetica'
  Player:
    IconColor: '255, 255, 0'
    IconShape: Cross
    IconSize: 8
    IconThickness: 2
  SuperChest:
    IconColor: '17, 255, 0'
    IconShape: Square
    IconSize: 4
  NormalChest:
    IconColor: '96, 96, 96'
    IconShape: Square
    IconSize: 3
  Shrine:
    IconColor: '255, 218, 100'
    IconShape: Polygon
    IconSize: 5
  ArmorWeapRack:
    IconColor: '132, 132, 132'
    IconShape: Square
    IconSize: 4
  Item: 
    IconColor: 'DarkOrange'
    IconShape: Ellipse
    IconSize: 4
    LabelFont: 'Helvetica'
    LabelFontSize: 10

## ItemLog - Alerts for in-game dropped items nearby
ItemLog:
  Enabled: false
  FilterFileName: "ItemFilter.yaml"
  ## PlaySoundOnDrop - Play drop sound
  PlaySoundOnDrop: false
  ## SoundFile - Name of .wav file for drop sound (put .wav file in the MapAssist folder)
  SoundFile: ""
  DisplayForSeconds: 45
  LabelFont: "Helvetica"
  LabelFontSize: 14

## MapColorConfiguration - Color schema for drawing overlay map
MapColorConfiguration:
  Walkable: '40, 40, 40'
  Border: '90, 90, 90'

## GameInfo - Displaying game server IP address
GameInfo:
  Enabled: false
  ## ShowOverlayFPS - Developer setting, probably not useful
  ShowOverlayFPS: false

## HuntingIP - Set an IP address to display in green instead of red
HuntingIP: 'x.x.x.x'

## Path to D2LOD installation. Optional.
## Should only need to provide if we are not able to look it up
## automatically via the registry
D2Path: ''

## UpdateTime - Advanced setting for how often to read the game memory in ms
UpdateTime: 30

## ClearPrefetchedOnAreaChange - Advanced setting for clearing prefetched cache
ClearPrefetchedOnAreaChange: true