# Change these settings from the Config GUI provided in MapAssist
HotkeyConfiguration:
  ToggleKey: '|'
  HideMapKey: ''
  MapPositionsKey: ''
  ZoomInKey: Num +
  ZoomOutKey: Num -
  ExportItemsKey: F9
  ToggleConfigKey: F12
HiddenAreas:
- Forgotten Tower
AuthorizedWindowTitles: []
RenderingConfiguration:
  Opacity: 0.3
  IconOpacity: 0.9
  OverlayMode: true
  Position: Center
  MonsterHealthBar: true
  ToggleViaInGameMap: false
  ToggleViaInGamePanels: true
  StickToLastGameWindow: true
  Size: 800
  ZoomLevel: 1
  BuffSize: 1
  ShowBuffBarBuffs: true
  ShowBuffBarAuras: true
  ShowBuffBarPassives: true
  ShowBuffBarDebuffs: true
  BuffAlertLowRes: true
  BuffPosition: Bottom
  ShowLife: false
  ShowLifePerc: true
  ShowMana: false
  ShowManaPerc: true
  ShowCurrentLevel: false
  ShowExpProgress: true
  ShowPotionBelt: true
  ShowResistances: false
MapConfiguration:
  SuperUniqueMonster:
    IconOutlineColor: Yellow
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  UniqueMonster:
    IconOutlineColor: DarkOrange
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  ChampionMonster:
    IconOutlineColor: DarkRed
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  MinionMonster:
    IconOutlineColor: 255, 150, 150
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  NormalMonster:
    IconOutlineColor: Gray
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  Npc:
    IconSize: 0
    LabelColor: 199, 179, 119
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  NextArea:
    IconSize: 0
  PreviousArea:
    IconSize: 0
  Waypoint:
    IconSize: 0
  Quest:
    IconSize: 0
  Player:
    IconSize: 0
  PartyPlayer:
    IconSize: 0
  NonPartyPlayer:
    IconSize: 0
  HostilePlayer:
    IconSize: 0
    LineColor: Red
    LineThickness: 2
    ArrowHeadSize: 15
  MyMerc:
    IconSize: 0
  OtherMercs:
    IconSize: 0
  MySummons:
    IconOutlineColor: 77, 120, 124
    IconShape: Cross
    IconSize: 6
    IconThickness: 0
  OtherSummons:
    IconOutlineColor: 81, 167, 60
    IconShape: Cross
    IconSize: 6
    IconThickness: 0
  Corpse:
    IconOutlineColor: Magenta
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LineColor: Magenta
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Magenta
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  MyPortal:
    IconSize: 0
    LabelColor: Yellow
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  PartyPortal:
    IconSize: 0
    LabelColor: Yellow
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  NonPartyPortal:
    IconSize: 0
    LabelColor: Orange
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  GamePortal:
    IconSize: 0
  SuperChest:
    IconSize: 0
    LabelFontSize: 0
  NormalChest:
    IconColor: 17, 128, 0
    IconShape: Square
    IconSize: 3
  LockedChest:
    IconColor: Maroon
    IconShape: Square
    IconSize: 3
  TrappedChest:
    IconColor: Red
    IconShape: Square
    IconSize: 4
  Shrine:
    IconSize: 0
    LabelColor: 255, 218, 100
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  ArmorWeapRack:
    IconColor: 132, 132, 132
    IconShape: Square
    IconSize: 4
  Door:
    IconSize: 0
  Item:
    IconColor: DarkOrange
    IconShape: Ellipse
    IconSize: 4
    LabelFontSize: 16
    LabelFont: Exocet Blizzard Mixed Caps
    LabelTextShadow: true
  MissilePhysicalLarge:
    IconColor: 255, 194, 194
    IconShape: Ellipse
    IconSize: 8
    IconOpacity: 0.66
  MissilePhysicalSmall:
    IconColor: 201, 157, 157
    IconShape: Ellipse
    IconSize: 5
    IconOpacity: 0.66
  MissileFireLarge:
    IconColor: Red
    IconShape: Ellipse
    IconSize: 8
    IconOpacity: 0.66
  MissileFireSmall:
    IconColor: 194, 0, 0
    IconShape: Ellipse
    IconSize: 5
    IconOpacity: 0.66
  MissileIceLarge:
    IconColor: 0, 208, 255
    IconShape: Ellipse
    IconSize: 8
    IconOpacity: 0.66
  MissileIceSmall:
    IconColor: 0, 208, 255
    IconShape: Ellipse
    IconSize: 5
    IconOpacity: 0.66
  MissileLightLarge:
    IconColor: Yellow
    IconShape: Ellipse
    IconSize: 8
    IconOpacity: 0.66
  MissileLightSmall:
    IconColor: 163, 163, 0
    IconShape: Ellipse
    IconSize: 5
    IconOpacity: 0.66
  MissilePoisonLarge:
    IconColor: Lime
    IconShape: Ellipse
    IconSize: 8
    IconOpacity: 0.66
  MissilePoisonSmall:
    IconColor: 0, 156, 0
    IconShape: Ellipse
    IconSize: 5
    IconOpacity: 0.66
  MissileMagicLarge:
    IconColor: 255, 115, 0
    IconShape: Ellipse
    IconSize: 8
    IconOpacity: 0.66
  MissileMagicSmall:
    IconColor: 179, 80, 0
    IconShape: Ellipse
    IconSize: 5
    IconOpacity: 0.66
ItemLog:
  Enabled: true
  Position: TopLeft
  FilterFileName: ItemFilter.yaml
  CheckVendorItems: true
  CheckItemOnIdentify: true
  PlaySoundOnDrop: true
  ShowDistanceToItem: true
  ShowDirectionToItem: true
  SoundFile: 'Ching.wav'
  SoundVolume: 100
  DisplayForSeconds: 45
  LabelFont: Exocet Blizzard Mixed Caps
  LabelFontSize: 16
  LabelTextShadow: true
  SuperiorColor: Gray
  MagicColor: RoyalBlue
  RareColor: Yellow
  SetColor: Lime
  UniqueColor: 165, 146, 99
  CraftedColor: 255, 174, 0
MapColorConfiguration:
  Border: White
GameInfo:
  Position: TopLeft
  ShowGameName: true
  ShowArea: true
  ShowAreaLevel: true
  ShowDifficulty: true
  ShowOverlayFPS: false
  ShowGameTimer: true
  ShowAreaTimer: true
  LabelFont: Exocet Blizzard Mixed Caps
  LabelFontSize: 16
  LabelTextShadow: true
D2Path: ''
LanguageCode: enUS
DPIAware: false
