#---
# How often to read the game memory
# You likely shouldn't change this
UpdateTime: 20

# Areas to preload so that they're hot and ready as soon as you go to them
PrefetchAreas:
 - 'Catacombs Level 2'
#...
MapConfiguration:
  SuperUniqueMonster:
    IconColor: Purple
    IconShape: Square