## HotkeyConfiguration - Keyboard shortcuts for the overlay
HotkeyConfiguration:
  ToggleKey: '\'
  ZoomInKey: '+'
  ZoomOutKey: '-'
  GameInfoKey: '['

## PrefetchAreas - Areas to preload so that they're hot and ready as soon as you go to them
PrefetchAreas:
 - 'Catacombs Level 2'
 - 'Durance Of Hate Level 2'

## HiddenAreas - Areas where the overlay is not needed and will be hidden
HiddenAreas:
 - 'Rogue Encampment'
 - 'Lut Gholein'
 - 'Kurast Docktown'
 - 'The Pandemonium Fortress'
 - 'Harrogath'
 - 'Forgotten Tower'
 - 'Nihlathaks Temple'

## RenderingConfiguration - Visual settings for the overlay
RenderingConfiguration:
  ## Opacity - Overlay trapsparency %
  Opacity: 0.5
  ## OverlayMode - Overlay map over in-game map / can be hidden with hotkey (ToggleKey)
  OverlayMode: true
  ## Positions - Options are: Center, TopLeft, TopRight
  Position: Center
  ## ToggleViaInGameMap - Auto-hide overlay when in-game map closes
  ToggleViaInGameMap: false
  ## ToggleViaInGamePanels - Auto-hide overlay when in-game panels/menus open
  ToggleViaInGamePanels: false
  ## Size - Overlay map maximum size
  Size: 450
  ## Rotate - Transform map image with 45° rotation
  Rotate: true
  ## ZoomLevel - Zoom level / can zoom in/out with hotkeys (ZoomInKey, ZoomOutKey)
  ZoomLevel: 1
  ## BuffPosition - Options are: Center, Bottom
  BuffPosition: Bottom
  ## BuffSize - Size of the buff icons (0.8 = 80%, 1 = 100%, 1.2 = 120%)
  BuffSize: 1

## MapConfiguration -- Visual settings for icons, lines and labels
MapConfiguration:
  SuperUniqueMonster:
    IconColor: Yellow
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  UniqueMonster:
    IconColor: DarkOrange
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  EliteMonster:
    IconColor: DarkRed
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  NormalMonster:
    IconColor: Gray
    IconShape: SquareOutline
    IconSize: 6
    IconThickness: 2
  NextArea:
    IconColor: '237, 107, 0'
    IconShape: Square
    IconSize: 10
    LineColor: Chartreuse
    LineThickness: 2
    ArrowHeadSize: 10
    LabelColor: Chartreuse
    LabelFontSize: 8
    LabelFont: 'Helvetica'
  PreviousArea:
    IconColor: '255, 0, 149'
    IconShape: Square
    IconSize: 10
    LineColor: ''
    LabelColor: Chartreuse
    LabelFontSize: 8
    LabelFont: 'Helvetica'
  Waypoint:
    IconColor: '16, 140, 235'
    IconShape: Square
    IconSize: 10
  Quest:
    LineColor: Chartreuse
    LineThickness: 2
    ArrowHeadSize: 5
  Player:
    IconColor: '255, 255, 0'
    IconShape: Square
    IconSize: 5
    IconThickness: 2
  SuperChest:
    IconColor: '17, 255, 0'
    IconShape: Ellipse
    IconSize: 10
  NormalChest:
    IconColor: '96, 96, 96'
    IconShape: Square
    IconSize: 5
  Shrine:
    IconColor: '255, 218, 100'
    IconShape: Polygon
    IconSize: 10
  ArmorWeapRack:
    IconColor: '132, 132, 132'
    IconShape: Square
    IconSize: 4
  Item: 
    IconColor: 'DarkOrange'
    IconShape: Ellipse
    IconSize: 6
    LabelFont: 'Helvetica'
    LabelFontSize: 8

## MapColorConfiguration - Color schema for drawing overlay map
MapColorConfiguration:
  MapColors:
    '0': '50, 50, 50'
    '2': '10, 51, 23'
    '3': '255, 255, 255'
    '4': '0, 255, 255'
    '6': '50, 50, 50'
    '7': '0, 0, 0'
    '16': '50, 50, 50'
    '17': '50, 50, 50'
    '19': '100, 100, 100'
    '20': '40, 40, 40'
    '21': '50, 50, 50'
    '23': '120, 120, 120'
    '33': '0, 0, 0'
    '37': '0, 0, 0'
    '39': '0, 0, 0'
    '53': '0, 0, 0'

## ItemLog - Alerts for in-game dropped items nearby
ItemLog:
  Enabled: true
  FilterFileName: "ItemFilter.yaml"
  ## PlaySoundOnDrop - Play drop sound
  PlaySoundOnDrop: true
  ## SoundFile - Name of .wav file for drop sound (put .wav file in the MapAssist folder)
  SoundFile: ""
  DisplayForSeconds: 45
  LabelFont: "Helvetica"
  LabelFontSize: 14

## GameInfo - Displaying game server IP address
GameInfo:
  Enabled: true
  ## ShowOverlayFPS - Developer setting, probably not useful
  ShowOverlayFPS: false

## HuntingIP - Set an IP address to display in green instead of red
HuntingIP: 'x.x.x.x'

## ApiConfiguration - Connection to d2mapapi service
ApiConfiguration:
  Endpoint: 'http://localhost:8080/'
  Token: ''

## UpdateTime - Advanced setting for how often to read the game memory in ms
UpdateTime: 30

## ClearPrefetchedOnAreaChange - Advanced setting for clearing prefetched cache
ClearPrefetchedOnAreaChange: true