name: Rebase after merge

on: 
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  rebase:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: Rebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
